apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-2-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-2-frontend
  template:
    metadata:
      labels:
        app: devops-2-frontend
    spec:
      containers:
        - name: devops-2-frontend
          image: devops-2-frontend
          env:
            - name: VITE_API_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: VITE_API_URL
          ports:
            - containerPort: 8000
