apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: devops-2-frontend
  newName: gbrlls/devops-2-frontend
  newTag: d871b14abcbe7368474eec950e375c8048e9906f
