apiVersion: v1
kind: Service
metadata:
  name: devops-2-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: devops-2-frontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
