apiVersion: v1
kind: Service
metadata:
  name: devops-2-frontend-service
spec:
  type: NodePort
  selector:
    app: devops-2-frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30500
